apiVersion: v1
kind: LimitRange
metadata:
  name: default-resources
  namespace: argocd
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 100m
        memory: 128Mi
      default:
        cpu: 500m
        memory: 512Mi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-resources
  namespace: cert-manager
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 25m
        memory: 32Mi
      default:
        cpu: 125m
        memory: 128Mi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-resources
  namespace: monitoring
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 100m
        memory: 128Mi
      default:
        cpu: 500m
        memory: 512Mi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-resources
  namespace: kube-system
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 25m
        memory: 32Mi
      default:
        cpu: 125m
        memory: 128Mi
